# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'
      vstsFeed: 'BuildingBlocks/building-blocks.internal'
      includeNuGetOrg: true
  - task: DotNetCoreCLI@2
    displayName: 'Create NuGet package'
    inputs:
      command: pack
      arguments: '--no-restore'
      versioningScheme: off

  - task: DotNetCoreCLI@2
    displayName: 'Publish to internal feed'
    inputs:
      command: 'push'
      arguments: '--skip-duplicate'
      searchPatternPush: '$(Build.ArtifactStagingDirectory)/BuildingBlocks*.nupkg'
      publishVstsFeed: 'BuildingBlocks/building-blocks.internal'
      nuGetFeedType: 'internal'