// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class ContactMedium
    {
        public ContactMedium()
        {
            PartyRoleContactableVia = new HashSet<PartyRoleContactableVia>();
        }

        public long Id { get; set; }
        public string Value { get; set; }
        public int ContactMediumClassId { get; set; }

        public virtual ContactMediumClass ContactMediumClass { get; set; }
        public virtual ICollection<PartyRoleContactableVia> PartyRoleContactableVia { get; set; }
    }
}