// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class Document
    {
        public Document()
        {
            EntityDocuments = new HashSet<EntityDocument>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public byte[] Binary { get; set; }
        public int? DocumentTemplateId { get; set; }
        public string Extension { get; set; }
        public DateTime RecordedTimeStamp { get; set; }
        public string ContentType { get; set; }
        public string Tags { get; set; }
        public int DocumentDefinitionId { get; set; }
        public Guid RecordId { get; set; }
        public Guid? ExternalId { get; set; }
        public bool IsSynced { get; set; }
        public virtual DocumentTemplate DocumentTemplate { get; set; }
        public virtual MimeType ExtensionNavigation { get; set; }
        public virtual ICollection<EntityDocument> EntityDocuments { get; set; }
    }
}