// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class DocumentTemplate
    {
        public DocumentTemplate()
        {
            Documents = new HashSet<Document>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] Binary { get; set; }
        public string Extension { get; set; }

        public virtual MimeType ExtensionNavigation { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
    }
}