// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class EntitySpecLifeCycleOperation
    {
        public int EntitySpecificationId { get; set; }
        public int LifeCycleId { get; set; }
        public int OperationId { get; set; }

        public virtual EntitySpecification EntitySpecification { get; set; }
        public virtual LifeCycle LifeCycle { get; set; }
        public virtual Operation Operation { get; set; }
    }
}