// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class EntityLifeCycleHistoryLog
    {
        public long Id { get; set; }
        public long EntityId { get; set; }
        public int PreviousLifeCycleId { get; set; }
        public int CurrentLifeCycleId { get; set; }
        public int TransationId { get; set; }
        public DateTime TransitionTimeStamp { get; set; }
        public long? EntityInvolvementRoleId { get; set; }

        public virtual Entity Entity { get; set; }
        public virtual LifeCycleTransitionTable LifeCycleTransitionTable { get; set; }
    }
}