// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class EntitySpecification
    {
        public EntitySpecification()
        {
            Entities = new HashSet<Entity>();
            EntitySpecInvolvementRoleTypes = new HashSet<EntitySpecInvolvementRoleType>();
            EntitySpecLifeCycleOperations = new HashSet<EntitySpecLifeCycleOperation>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsSearchable { get; set; }
        public int? LifeCycleClassDefinitionId { get; set; }

        public virtual LifeCycleClassDefinition LifeCycleClassDefinition { get; set; }
        public virtual ICollection<Entity> Entities { get; set; }
        public virtual ICollection<EntitySpecInvolvementRoleType> EntitySpecInvolvementRoleTypes { get; set; }
        public virtual ICollection<EntitySpecLifeCycleOperation> EntitySpecLifeCycleOperations { get; set; }
    }
}