// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class EntitySpecInvolvementRoleType
    {
        public EntitySpecInvolvementRoleType()
        {
            EntitySpecInvolvRoleTypeUses = new HashSet<EntitySpecInvolvRoleTypeUse>();
        }

        public int Id { get; set; }
        public int InvolvementRoleTypeId { get; set; }
        public int EntitySpecificationId { get; set; }
        public int MinCardinality { get; set; }
        public int? MaxCardinality { get; set; }

        public virtual EntitySpecification EntitySpecification { get; set; }
        public virtual InvolvementRoleType InvolvementRoleType { get; set; }
        public virtual ICollection<EntitySpecInvolvRoleTypeUse> EntitySpecInvolvRoleTypeUses { get; set; }
    }
}