// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class Entity
    {
        public Entity()
        {
            EntityDocuments = new HashSet<EntityDocument>();
            EntityInvolvementRoles = new HashSet<EntityInvolvementRole>();
            EntityLifeCycleHistoryLogs = new HashSet<EntityLifeCycleHistoryLog>();
            EntityOperationLogs = new HashSet<EntityOperationLog>();
            EntityProcessLogs = new HashSet<EntityProcessLog>();
        }

        public long Id { get; set; }
        public Guid RecordId { get; set; }
        public DateTime RecordedTimeStamp { get; set; }
        public int RecordedByPartyId { get; set; }
        public DateTime LifeCycleChangeTime { get; set; }
        public int? LifeCycleChangeByPartyId { get; set; }
        public int LifeCycleId { get; set; }
        public int EntitySpecificationId { get; set; }
        public int? ModifiedByPartyId { get; set; }
        public DateTime? ModifiedTimeStamp { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime? DeletedDate { get; set; }

        public virtual EntitySpecification EntitySpecification { get; set; }
        public virtual LifeCycle LifeCycle { get; set; }
        public virtual Individual LifeCycleChangeByParty { get; set; }
        public virtual Individual ModifiedByParty { get; set; }
        public virtual Individual RecordedByParty { get; set; }
     
        public virtual ICollection<EntityDocument> EntityDocuments { get; set; }
        public virtual ICollection<EntityInvolvementRole> EntityInvolvementRoles { get; set; }
        public virtual ICollection<EntityLifeCycleHistoryLog> EntityLifeCycleHistoryLogs { get; set; }
        public virtual ICollection<EntityOperationLog> EntityOperationLogs { get; set; }
        public virtual ICollection<EntityProcessLog> EntityProcessLogs { get; set; }
    }
}