// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class GetEntityDocumentDownloadResult
    {
        public string FileName { get; set; }
        public string ContentType { get; set; }
        public byte[] Binary { get; set; }
    }
}
