// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class IdentificationSchema
    {
        public IdentificationSchema()
        {
            Parties = new HashSet<Party>();
        }

        public int Id { get; set; }
        public Guid GlobalId { get; set; }
        public string Name { get; set; }
        public string Uri { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Party> Parties { get; set; }
    }
}