// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class Individual
    {
        public Individual()
        {
            EntityLifeCycleChangeByParties = new HashSet<Entity>();
            EntityModifiedByParties = new HashSet<Entity>();
            EntityRecordedByParties = new HashSet<Entity>();
        }

        public int Id { get; set; }
        public string GivenName { get; set; }
        public string MiddleName { get; set; }
        public string FamilyName { get; set; }
        public string Username { get; set; }

        public DateTime? AliveDuringFrom { get; set; }
        public DateTime? AliveDuringDue { get; set; }
 
        public virtual Party Party { get; set; }
        public virtual ICollection<Entity> EntityLifeCycleChangeByParties { get; set; }
        public virtual ICollection<Entity> EntityModifiedByParties { get; set; }
        public virtual ICollection<Entity> EntityRecordedByParties { get; set; }
    }
}