// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class InvolvementRoleTypePartyRoleTypeInvolf
    {
        public int InvolvementRoleTypeId { get; set; }
        public int PartyRoleTypeId { get; set; }

        public virtual InvolvementRoleType InvolvementRoleType { get; set; }
        public virtual PartyRoleType PartyRoleType { get; set; }
    }
}