// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class InvolvementRole
    {
        public long Id { get; set; }
        public int InvolvementRoleTypeId { get; set; }
        public DateTime ValidFrom { get; set; }
        public DateTime? ValidDue { get; set; }
        public bool IsActive { get; set; }
        public long? PartyRoleId { get; set; }

        public virtual InvolvementRoleType InvolvementRoleType { get; set; }
        public virtual PartyRole PartyRole { get; set; }
        public virtual EntityInvolvementRole EntityInvolvementRole { get; set; }
    }
}