// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class LifeCycleClassDefLifeCycleTran
    {
        public int LifeCycleClassDefinitionId { get; set; }
        public int LifeCycleTransitionId { get; set; }

        public virtual LifeCycleClassDefinition LifeCycleClassDefinition { get; set; }
        public virtual LifeCycleTransition LifeCycleTransition { get; set; }
    }
}