// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class LifeCycleStateType
    {
        public LifeCycleStateType()
        {
            LifeCycles = new HashSet<LifeCycle>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<LifeCycle> LifeCycles { get; set; }
    }
}