// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class LifeCycleTransitionTable
    {
        public LifeCycleTransitionTable()
        {
            EntityLifeCycleHistoryLogs = new HashSet<EntityLifeCycleHistoryLog>();
        }

        public int CurrentLifeCycleId { get; set; }
        public int NextLifeCycleId { get; set; }
        public int TransitionId { get; set; }

        public virtual LifeCycle CurrentLifeCycle { get; set; }
        public virtual LifeCycle NextLifeCycle { get; set; }
        public virtual LifeCycleTransition Transition { get; set; }
        public virtual ICollection<EntityLifeCycleHistoryLog> EntityLifeCycleHistoryLogs { get; set; }
    }
}