// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class LifeCycle
    {
        public LifeCycle()
        {
            Entities = new HashSet<Entity>();
            EntitySpecLifeCycleOperations = new HashSet<EntitySpecLifeCycleOperation>();
            LifeCycleTransitionTableCurrentLifeCycles = new HashSet<LifeCycleTransitionTable>();
            LifeCycleTransitionTableNextLifeCycles = new HashSet<LifeCycleTransitionTable>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int LifeCycleStateTypeId { get; set; }
        public int LifeCycleClassDefinitionId { get; set; }

        public virtual LifeCycleClassDefinition LifeCycleClassDefinition { get; set; }
        public virtual LifeCycleStateType LifeCycleStateType { get; set; }
        public virtual ICollection<Entity> Entities { get; set; }
        public virtual ICollection<EntitySpecLifeCycleOperation> EntitySpecLifeCycleOperations { get; set; }
        public virtual ICollection<LifeCycleTransitionTable> LifeCycleTransitionTableCurrentLifeCycles { get; set; }
        public virtual ICollection<LifeCycleTransitionTable> LifeCycleTransitionTableNextLifeCycles { get; set; }
    }
}