// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class MimeType
    {
        public MimeType()
        {
            DocumentTemplates = new HashSet<DocumentTemplate>();
            Documents = new HashSet<Document>();
        }

        public string Extension { get; set; }
        public string CommonName { get; set; }
        public string Description { get; set; }
        public bool FullTextSearchable { get; set; }

        public virtual ICollection<DocumentTemplate> DocumentTemplates { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
    }
}