// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class Operation
    {
        public Operation()
        {
            EntityOperationLogs = new HashSet<EntityOperationLog>();
            EntityProcessLogs = new HashSet<EntityProcessLog>();
            EntitySpecLifeCycleOperations = new HashSet<EntitySpecLifeCycleOperation>();
            OperationInvolvementRoleTypes = new HashSet<OperationInvolvementRoleType>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public virtual ICollection<EntityOperationLog> EntityOperationLogs { get; set; }
        public virtual ICollection<EntityProcessLog> EntityProcessLogs { get; set; }
        public virtual ICollection<EntitySpecLifeCycleOperation> EntitySpecLifeCycleOperations { get; set; }
        public virtual ICollection<OperationInvolvementRoleType> OperationInvolvementRoleTypes { get; set; }
    }
}