// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class Organization
    {
        public int Id { get; set; }
        public string TradingName { get; set; }
        public DateTime ExistingDuringFrom { get; set; }
        public DateTime? ExistingDuringDue { get; set; }
        public string Type { get; set; }
        public string LongName { get; set; }
        public string Code { get; set; }
        public string AddressStreetAndBuildingNumber { get; set; }
        public string AddressPostalOfficeCode { get; set; }
        public string AddressCity { get; set; }
        public string AddressCountry { get; set; }

        public string AddressLine { get; set; }
        public int Level { get; set; }
        public virtual Party Party { get; set; }
    }
}