// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class PartyRoleContactableVia
    {
        public long ContactMediumId { get; set; }
        public long PartyRoleId { get; set; }

        public virtual ContactMedium ContactMedium { get; set; }
        public virtual PartyRole PartyRole { get; set; }
    }
}