// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class PartyRoleType
    {
        public PartyRoleType()
        {
            InverseParentClass = new HashSet<PartyRoleType>();
            InvolvementRoleTypePartyRoleTypeInvolves = new HashSet<InvolvementRoleTypePartyRoleTypeInvolf>();
            PartyRoles = new HashSet<PartyRole>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int PartyRoleTypeDiscriminatorId { get; set; }
        public int? ParentClassId { get; set; }

        public virtual PartyRoleType ParentClass { get; set; }
        public virtual PartyRoleTypeDiscriminator PartyRoleTypeDiscriminator { get; set; }
        public virtual ICollection<PartyRoleType> InverseParentClass { get; set; }
        public virtual ICollection<InvolvementRoleTypePartyRoleTypeInvolf> InvolvementRoleTypePartyRoleTypeInvolves { get; set; }
        public virtual ICollection<PartyRole> PartyRoles { get; set; }
    }
}