// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class Party
    {
        public Party()
        {
            CatalogItems = new HashSet<CatalogItem>();
            PartyRoles = new HashSet<PartyRole>();
            Users = new HashSet<ApplicationUser>();
        }

        public int Id { get; set; }
        public Guid GlobalId { get; set; }
        public string ExternalId { get; set; }
        public int? ExternalIdIdentificationSchemaId { get; set; }
        public string AdditionalExternalId { get; set; }
        public int? AdditionalExternalIDIdentificationSchemaId { get; set; }
        public virtual IdentificationSchema ExternalIdidentificationSchema { get; set; }
        public virtual Individual Individual { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<CatalogItem> CatalogItems { get; set; }
        public virtual ICollection<PartyRole> PartyRoles { get; set; }
        public virtual ICollection<ApplicationUser> Users { get; set; }
        public int Level { get; set; }
    }
}