// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class PartyRoleAssociation
    {
        public PartyRoleAssociation()
        {
            PermissionPartyRoleAssociations = new HashSet<PermissionPartyRoleAssociation>();
        }

        public int Id { get; set; }
        public long PartyRoleInvolvedWithId { get; set; }
        public long PartyRoleInvolvesId { get; set; }
        public int PartyRoleAssociationTypeId { get; set; }
        public DateTime ValidFrom { get; set; }
        public DateTime? ValidDue { get; set; }
        public bool IsActive { get; set; }
        public string Status { get; set; }

        public virtual PartyRoleAssociationType PartyRoleAssociationType { get; set; }
        public virtual PartyRole PartyRoleInvolvedWith { get; set; }
        public virtual PartyRole PartyRoleInvolves { get; set; }
        public virtual ICollection<PermissionPartyRoleAssociation> PermissionPartyRoleAssociations { get; set; }
    }
}