// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class PermissionPartyRoleAssociation
    {
        public int PermissionId { get; set; }
        public int PartyRoleAssociationId { get; set; }

        public virtual PartyRoleAssociation PartyRoleAssociation { get; set; }
        public virtual Permission Permission { get; set; }
    }
}