// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class PermissionRelationship
    {
        public int PermissionId { get; set; }
        public int RelatedPermissionId { get; set; }

        public virtual Permission Permission { get; set; }
        public virtual Permission RelatedPermission { get; set; }
    }
}