// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SC.API.CleanArchitecture.Domain.Entities
{
    public partial class Permission
    {
        public Permission()
        {
            PermissionPartyRoleAssociations = new HashSet<PermissionPartyRoleAssociation>();
            PermissionRelationshipPermissions = new HashSet<PermissionRelationship>();
            PermissionRelationshipRelatedPermissions = new HashSet<PermissionRelationship>();
            PermissionTemplatePermissions = new HashSet<PermissionTemplatePermission>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int PermissionTypeId { get; set; }
        public int PermissionLevelId { get; set; }
        public int? PermissionGroupId { get; set; }
        public string Description { get; set; }

        public virtual PermissionGroup PermissionGroup { get; set; }
        public virtual PermissionLevel PermissionLevel { get; set; }
        public virtual PermissionType PermissionType { get; set; }
        public virtual ICollection<PermissionPartyRoleAssociation> PermissionPartyRoleAssociations { get; set; }
        public virtual ICollection<PermissionRelationship> PermissionRelationshipPermissions { get; set; }
        public virtual ICollection<PermissionRelationship> PermissionRelationshipRelatedPermissions { get; set; }
        public virtual ICollection<PermissionTemplatePermission> PermissionTemplatePermissions { get; set; }
    }
}