// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SC.API.CleanArchitecture.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace SC.API.CleanArchitecture.Infrastructure.Persistence.Configurations
{
    public class DocumentConfiguration : IEntityTypeConfiguration<Document>
    {
        public void Configure(EntityTypeBuilder<Document> entity)
        {
            entity.ToTable("Document");

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.Binary).IsRequired();

            entity.Property(e => e.ContentType)
                .IsRequired()
                .HasMaxLength(510);

            entity.Property(e => e.DocumentDefinitionId).HasColumnName("DocumentDefinitionID");

            entity.Property(e => e.DocumentTemplateId).HasColumnName("DocumentTemplateID");

            entity.Property(t => t.RecordId).HasColumnName("RecordID");

            entity.Property(t => t.ExternalId).HasColumnName("ExternalID");

            entity.Property(e => e.Extension)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false);

            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(255);

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);

            entity.Property(e => e.RecordedTimeStamp)
                 .HasDefaultValueSql("CURRENT_TIMESTAMP");

            entity.HasOne(d => d.DocumentTemplate)
                .WithMany(p => p.Documents)
                .HasForeignKey(d => d.DocumentTemplateId)
                .HasConstraintName("FK_Document_DocumentTemplate1");

            entity.HasOne(d => d.ExtensionNavigation)
                .WithMany(p => p.Documents)
                .HasForeignKey(d => d.Extension)
                .OnDelete(DeleteBehavior.ClientSetNull);
                //.HasConstraintName("FK_Document_MimeType");
        }
    }
}
