// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SC.API.CleanArchitecture.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace SC.API.CleanArchitecture.Infrastructure.Persistence.Configurations
{
    public class EntityOperationLogConfiguration : IEntityTypeConfiguration<EntityOperationLog>
    {
        public void Configure(EntityTypeBuilder<EntityOperationLog> entity)
        {
            entity.ToTable("EntityOperationLog");

            entity.Property(e => e.Id)
                .HasColumnName("ID")
                .ValueGeneratedNever();

            entity.Property(e => e.ApplicationUserId)
                .IsRequired()
                .HasColumnName("ApplicationUserId")
                .HasMaxLength(450);

            entity.Property(e => e.EntityId).HasColumnName("EntityID");

            entity.Property(e => e.NewObject).IsRequired();

            entity.Property(e => e.OldObject).IsRequired();

            entity.Property(e => e.OperationId).HasColumnName("OperationID");

            entity.Property(e => e.Timestamp)
                 .HasDefaultValueSql("CURRENT_TIMESTAMP");

            entity.HasOne(d => d.ApplicationUser)
                .WithMany(p => p.EntityOperationLogs)
                .HasForeignKey(d => d.ApplicationUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EntityOperationLog_AspNetUsers");

            entity.HasOne(d => d.Entity)
                .WithMany(p => p.EntityOperationLogs)
                .HasForeignKey(d => d.EntityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EntityOperationLog_Entity");

            entity.HasOne(d => d.Operation)
                .WithMany(p => p.EntityOperationLogs)
                .HasForeignKey(d => d.OperationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EntityOperationLog_Operation");
        }
    }
}
