// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SC.API.CleanArchitecture.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace SC.API.CleanArchitecture.Infrastructure.Persistence.Configurations
{
    public class EntityInvolvementRoleConfiguration : IEntityTypeConfiguration<EntityInvolvementRole>
    {
        public void Configure(EntityTypeBuilder<EntityInvolvementRole> entity)
        {
            entity.ToTable("EntityInvolvementRole");

            entity.HasIndex(e => e.EntityId);

            entity.HasIndex(e => e.Id);

            entity.Property(e => e.Id)
                .HasColumnName("ID")
                .ValueGeneratedNever();

            entity.Property(e => e.EntityId).HasColumnName("EntityID");

            entity.HasOne(d => d.Entity)
                .WithMany(p => p.EntityInvolvementRoles)
                .HasForeignKey(d => d.EntityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo.EntityInvolvementRole_dbo.Entity_EntityID");

            entity.HasOne(d => d.InvolvementRole)
                .WithOne(p => p.EntityInvolvementRole)
                .HasForeignKey<EntityInvolvementRole>(d => d.Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo.EntityInvolvementRole_dbo.InvolvementRole_ID");
        }
    }
}
