// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SC.API.CleanArchitecture.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace SC.API.CleanArchitecture.Infrastructure.Persistence.Configurations
{
    public class EntitySpecInvolvRoleTypeUseConfiguration : IEntityTypeConfiguration<EntitySpecInvolvRoleTypeUse>
    {
        public void Configure(EntityTypeBuilder<EntitySpecInvolvRoleTypeUse> entity)
        {
            entity.HasIndex(e => e.EntitySpecInvolvementRoleTypeId);

            entity.HasIndex(e => e.PartyRoleAssociationTypeId);

            entity.HasIndex(e => e.PartyRoleId);

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.EntitySpecInvolvementRoleTypeId).HasColumnName("EntitySpecInvolvementRoleTypeID");

            entity.Property(e => e.PartyRoleAssociationTypeId).HasColumnName("PartyRoleAssociationTypeID");

            entity.Property(e => e.PartyRoleId).HasColumnName("PartyRoleID");

            entity.HasOne(d => d.EntitySpecInvolvementRoleType)
                .WithMany(p => p.EntitySpecInvolvRoleTypeUses)
                .HasForeignKey(d => d.EntitySpecInvolvementRoleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo.EntitySpecInvolvRoleTypeUses_dbo.EntitySpecInvolvementRoleType_EntitySpecInvolvementRoleTypeID");

            entity.HasOne(d => d.PartyRoleAssociationType)
                .WithMany(p => p.EntitySpecInvolvRoleTypeUses)
                .HasForeignKey(d => d.PartyRoleAssociationTypeId)
                .HasConstraintName("FK_dbo.EntitySpecInvolvRoleTypeUses_dbo.PartyRoleAssociationType_PartyRoleAssociationTypeID");

            entity.HasOne(d => d.PartyRole)
                .WithMany(p => p.EntitySpecInvolvRoleTypeUses)
                .HasForeignKey(d => d.PartyRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo.EntitySpecInvolvRoleTypeUses_dbo.PartyRole_PartyRoleID");
        }
    }
}
