// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SC.API.CleanArchitecture.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace SC.API.CleanArchitecture.Infrastructure.Persistence.Configurations
{
    public class IndividualConfiguration : IEntityTypeConfiguration<Individual>
    {
        public void Configure(EntityTypeBuilder<Individual> entity)
        {
            entity.ToTable("Individual");

            entity.Property(e => e.Id)
                .HasColumnName("ID")
                .ValueGeneratedNever();

            entity.Property(e => e.FamilyName)
                .IsRequired()
                .HasMaxLength(255);


            entity.Property(e => e.GivenName)
                .IsRequired()
                .HasMaxLength(255);

            entity.Property(e => e.MiddleName).HasMaxLength(255);

            entity.HasOne(d => d.Party)
                .WithOne(p => p.Individual)
                .HasForeignKey<Individual>(d => d.Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Individual_Party");

            entity.Property(e => e.Username).IsRequired();
            entity.HasIndex(u => u.Username).IsUnique();
        } 
    }
}
