// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SC.API.CleanArchitecture.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace SC.API.CleanArchitecture.Infrastructure.Persistence.Configurations
{
    public class InvolvementRoleTypePartyRoleTypeInvolfConfiguration : IEntityTypeConfiguration<InvolvementRoleTypePartyRoleTypeInvolf>
    {
        public void Configure(EntityTypeBuilder<InvolvementRoleTypePartyRoleTypeInvolf> entity)
        {
            entity.HasKey(e => new { e.InvolvementRoleTypeId, e.PartyRoleTypeId });

            entity.HasIndex(e => e.InvolvementRoleTypeId);

            entity.HasIndex(e => e.PartyRoleTypeId);

            entity.Property(e => e.InvolvementRoleTypeId).HasColumnName("InvolvementRoleTypeID");

            entity.Property(e => e.PartyRoleTypeId).HasColumnName("PartyRoleTypeID");

            entity.HasOne(d => d.InvolvementRoleType)
                .WithMany(p => p.InvolvementRoleTypePartyRoleTypeInvolves)
                .HasForeignKey(d => d.InvolvementRoleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo.InvolvementRoleTypePartyRoleTypeInvolves_dbo.InvolvementRoleType_InvolvementRoleTypeID");

            entity.HasOne(d => d.PartyRoleType)
                .WithMany(p => p.InvolvementRoleTypePartyRoleTypeInvolves)
                .HasForeignKey(d => d.PartyRoleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo.InvolvementRoleTypePartyRoleTypeInvolves_dbo.PartyRoleType_PartyRoleTypeID");
        }
    }
}
