// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SC.API.CleanArchitecture.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace SC.API.CleanArchitecture.Infrastructure.Persistence.Configurations
{
    public class InvolvementRoleConfiguration : IEntityTypeConfiguration<InvolvementRole>
    {
        public void Configure(EntityTypeBuilder<InvolvementRole> entity)
        {
            entity.ToTable("InvolvementRole");

            entity.HasIndex(e => e.InvolvementRoleTypeId);

            entity.HasIndex(e => e.PartyRoleId);

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.InvolvementRoleTypeId).HasColumnName("InvolvementRoleTypeID");

            entity.Property(e => e.PartyRoleId).HasColumnName("PartyRoleID");

            entity.HasOne(d => d.InvolvementRoleType)
                .WithMany(p => p.InvolvementRoles)
                .HasForeignKey(d => d.InvolvementRoleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo.InvolvementRole_dbo.InvolvementRoleType_InvolvementRoleTypeID");

            entity.HasOne(d => d.PartyRole)
                .WithMany(p => p.InvolvementRoles)
                .HasForeignKey(d => d.PartyRoleId)
                .HasConstraintName("FK_dbo.InvolvementRole_dbo.PartyRole_PartyRoleID");
        }
    }
}
