// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SC.API.CleanArchitecture.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using SC.API.CleanArchitecture.Domain.Enums;
using System.Collections.Generic;
using System.Linq;

namespace SC.API.CleanArchitecture.Infrastructure.Persistence.Configurations
{
    public class InvolvementRoleTypeConfiguration : IEntityTypeConfiguration<InvolvementRoleType>
    {
        public void Configure(EntityTypeBuilder<InvolvementRoleType> entity)
        {
            entity.ToTable("InvolvementRoleType");

            entity.Property(e => e.Id)
                .HasColumnName("ID")
                .ValueGeneratedNever();

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);

            var enumValues = new List<int>((int[])Enum.GetValues(typeof(InvolvementRoleTypeEnum)));

            entity.HasData(enumValues.Select(t => new InvolvementRoleType() {
                Id = t,
                Name = ((InvolvementRoleTypeEnum)t).ToString()
            }));
        }
    }
}
