// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SC.API.CleanArchitecture.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace SC.API.CleanArchitecture.Infrastructure.Persistence.Configurations
{
    public class LifeCycleClassDefLifeCycleTranConfiguration : IEntityTypeConfiguration<LifeCycleClassDefLifeCycleTran>
    {
        public void Configure(EntityTypeBuilder<LifeCycleClassDefLifeCycleTran> entity)
        {
            entity.HasKey(e => new { e.LifeCycleClassDefinitionId, e.LifeCycleTransitionId });

            entity.ToTable("LifeCycleClassDefLifeCycleTran");

            entity.Property(e => e.LifeCycleClassDefinitionId).HasColumnName("LifeCycleClassDefinitionID");

            entity.Property(e => e.LifeCycleTransitionId).HasColumnName("LifeCycleTransitionID");

            entity.HasOne(d => d.LifeCycleClassDefinition)
                .WithMany(p => p.LifeCycleClassDefLifeCycleTrans)
                .HasForeignKey(d => d.LifeCycleClassDefinitionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LifeCycleClassDefLifeCycleTran_LifeCycleClassDefinition");

            entity.HasOne(d => d.LifeCycleTransition)
                .WithMany(p => p.LifeCycleClassDefLifeCycleTrans)
                .HasForeignKey(d => d.LifeCycleTransitionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LifeCycleClassDefLifeCycleTran_LifeCycleTransition");
        }
    }
}
