// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SC.API.CleanArchitecture.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace SC.API.CleanArchitecture.Infrastructure.Persistence.Configurations
{
    public class LifeCycleTransitionTableConfiguration : IEntityTypeConfiguration<LifeCycleTransitionTable>
    {
        public void Configure(EntityTypeBuilder<LifeCycleTransitionTable> entity)
        {
            entity.HasKey(e => new { e.CurrentLifeCycleId, e.TransitionId });

            entity.ToTable("LifeCycleTransitionTable");

            entity.HasIndex(e => e.CurrentLifeCycleId);

            entity.HasIndex(e => e.NextLifeCycleId);

            entity.Property(e => e.CurrentLifeCycleId).HasColumnName("CurrentLifeCycleID");

            entity.Property(e => e.TransitionId).HasColumnName("TransitionID");

            entity.Property(e => e.NextLifeCycleId).HasColumnName("NextLifeCycleID");

            entity.HasOne(d => d.CurrentLifeCycle)
                .WithMany(p => p.LifeCycleTransitionTableCurrentLifeCycles)
                .HasForeignKey(d => d.CurrentLifeCycleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo.LifeCycleTransitionTable_dbo.LifeCycle_CurrentLifeCycleID");

            entity.HasOne(d => d.NextLifeCycle)
                .WithMany(p => p.LifeCycleTransitionTableNextLifeCycles)
                .HasForeignKey(d => d.NextLifeCycleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo.LifeCycleTransitionTable_dbo.LifeCycle_NextLifeCycleID");

            entity.HasOne(d => d.Transition)
                .WithMany(p => p.LifeCycleTransitionTables)
                .HasForeignKey(d => d.TransitionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LifeCycleTransitionTable_LifeCycleTransition");
        }
    }
}
