// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SC.API.CleanArchitecture.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using SC.API.CleanArchitecture.Domain.Enums;
using System.Collections.Generic;
using System.Linq;

namespace SC.API.CleanArchitecture.Infrastructure.Persistence.Configurations
{
    public class LifeCycleStateTypeConfiguration : IEntityTypeConfiguration<LifeCycleStateType>
    {
        public void Configure(EntityTypeBuilder<LifeCycleStateType> entity)
        {
            entity.ToTable("LifeCycleStateType");

            entity.Property(e => e.Id)
                .HasColumnName("ID")
                .ValueGeneratedNever();

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(25);

            var enumValues = new List<int>((int[])Enum.GetValues(typeof(LifeCycleStateTypeEnum)));

            entity.HasData(enumValues.Select(t => new LifeCycleStateType() {
                Id = t,
                Name = ((LifeCycleStateTypeEnum)t).ToString()
            }));
        }
    }
}
