// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SC.API.CleanArchitecture.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace SC.API.CleanArchitecture.Infrastructure.Persistence.Configurations
{
    public class MimeTypeConfiguration : IEntityTypeConfiguration<MimeType>
    {
        public void Configure(EntityTypeBuilder<MimeType> entity)
        {
            entity.HasKey(e => e.Extension);

            entity.ToTable("MimeType");

            entity.Property(e => e.Extension)
                .HasMaxLength(25)
                .IsUnicode(false);

            entity.Property(e => e.CommonName).HasMaxLength(255);
        }
    }
}
