// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SC.API.CleanArchitecture.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace SC.API.CleanArchitecture.Infrastructure.Persistence.Configurations
{
    public class OperationInvolvementRoleTypeConfiguration : IEntityTypeConfiguration<OperationInvolvementRoleType>
    {
        public void Configure(EntityTypeBuilder<OperationInvolvementRoleType> entity)
        {
            entity.HasKey(e => new { e.OperationId, e.InvolvementRoleTypeId })
                .HasName("PK_dbo.OperationInvolvementRoleType");

            entity.ToTable("OperationInvolvementRoleType");

            entity.HasIndex(e => e.InvolvementRoleTypeId);

            entity.HasIndex(e => e.OperationId);

            entity.Property(e => e.OperationId).HasColumnName("OperationID");

            entity.Property(e => e.InvolvementRoleTypeId).HasColumnName("InvolvementRoleTypeID");

            entity.HasOne(d => d.InvolvementRoleType)
                .WithMany(p => p.OperationInvolvementRoleTypes)
                .HasForeignKey(d => d.InvolvementRoleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo.OperationInvolvementRoleType_dbo.InvolvementRoleType_InvolvementRoleTypeID");

            entity.HasOne(d => d.Operation)
                .WithMany(p => p.OperationInvolvementRoleTypes)
                .HasForeignKey(d => d.OperationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo.OperationInvolvementRoleType_dbo.Operation_OperationID");
        }
    }
}
