// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SC.API.CleanArchitecture.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace SC.API.CleanArchitecture.Infrastructure.Persistence.Configurations
{
    public class PartyRoleContactableViaConfiguration : IEntityTypeConfiguration<PartyRoleContactableVia>
    {
        public void Configure(EntityTypeBuilder<PartyRoleContactableVia> entity)
        {
            entity.HasKey(e => new { e.ContactMediumId, e.PartyRoleId });

            entity.HasIndex(e => e.ContactMediumId);
            entity.HasIndex(e => e.PartyRoleId);

            entity.Property(e => e.ContactMediumId).HasColumnName("ContactMediumID");

            entity.Property(e => e.PartyRoleId).HasColumnName("PartyRoleID");

            entity.HasOne(d => d.ContactMedium)
                .WithMany(p => p.PartyRoleContactableVia)
                .HasForeignKey(d => d.ContactMediumId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PartyRoleContactableVia_ContactMedium");

            entity.HasOne(d => d.PartyRole)
                .WithMany(p => p.PartyRoleContactableVia)
                .HasForeignKey(d => d.PartyRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PartyRoleContactableVia_PartyRole");
        }
    }
}
