// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SC.API.CleanArchitecture.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using SC.API.CleanArchitecture.Domain.Enums;

namespace SC.API.CleanArchitecture.Infrastructure.Persistence.Configurations
{
    public class PartyConfiguration : IEntityTypeConfiguration<Party>
    {
        public void Configure(EntityTypeBuilder<Party> entity)
        {
            entity.ToTable("Party");

            entity.HasIndex(e => new { e.ExternalIdIdentificationSchemaId, e.ExternalId })
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.ExternalId)
                .HasColumnName("ExternalID")
                .HasMaxLength(128);

            entity.Property(e => e.AdditionalExternalId)
                .HasColumnName("AdditionalExternalID")
                .HasMaxLength(128);

            entity.Property(e => e.AdditionalExternalIDIdentificationSchemaId)
                .HasColumnName("AdditionalExternalIDIdentificationSchemaID");

            entity.Property(e => e.ExternalIdIdentificationSchemaId).HasColumnName("ExternalIDIdentificationSchemaID");

            entity.Property(e => e.GlobalId)
                .HasColumnName("GlobalID")
                .HasDefaultValue(Guid.NewGuid());

            entity.HasOne(d => d.ExternalIdidentificationSchema)
                .WithMany(p => p.Parties)
                .HasForeignKey(d => d.ExternalIdIdentificationSchemaId)
                .HasConstraintName("FK_Party_IdentificationSchema");


            
        }
    }
}
