// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SC.API.CleanArchitecture.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using SC.API.CleanArchitecture.Domain.Enums;

namespace SC.API.CleanArchitecture.Infrastructure.Persistence.Configurations
{
    public class PartyRoleConfiguration : IEntityTypeConfiguration<PartyRole>
    {
        public void Configure(EntityTypeBuilder<PartyRole> entity)
        {
            entity.ToTable("PartyRole");

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.IsActive)
                .IsRequired()
                 .HasDefaultValue(true);

            entity.Property(e => e.JobTitle).HasMaxLength(510);
            entity.Property(e => e.JobCode).HasMaxLength(255);

            entity.Property(e => e.Name).HasMaxLength(255);

            entity.Property(e => e.PartyId).HasColumnName("PartyID");

            entity.Property(e => e.PartyRoleTypeId).HasColumnName("PartyRoleTypeID");

            entity.Property(e => e.ValidFrom)
                 .HasDefaultValueSql("CURRENT_TIMESTAMP");

            entity.HasOne(d => d.Party)
                .WithMany(p => p.PartyRoles)
                .HasForeignKey(d => d.PartyId)
                .HasConstraintName("FK_PartyRole_Party");

            entity.HasOne(d => d.PartyRoleType)
                .WithMany(p => p.PartyRoles)
                .HasForeignKey(d => d.PartyRoleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PartyRole_PartyRoleType");
        }
    }
}
