// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SC.API.CleanArchitecture.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace SC.API.CleanArchitecture.Infrastructure.Persistence.Configurations
{
    public class PermissionRelationshipConfiguration : IEntityTypeConfiguration<PermissionRelationship>
    {
        public void Configure(EntityTypeBuilder<PermissionRelationship> entity)
        {
            entity.HasKey(e => new { e.PermissionId, e.RelatedPermissionId });

            entity.ToTable("PermissionRelationship");

            entity.Property(e => e.PermissionId).HasColumnName("PermissionID");

            entity.Property(e => e.RelatedPermissionId).HasColumnName("RelatedPermissionID");

            entity.HasOne(d => d.Permission)
                .WithMany(p => p.PermissionRelationshipPermissions)
                .HasForeignKey(d => d.PermissionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PermissionRelationship_Permission");

            entity.HasOne(d => d.RelatedPermission)
                .WithMany(p => p.PermissionRelationshipRelatedPermissions)
                .HasForeignKey(d => d.RelatedPermissionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PermissionRelationship_Permission1");
        }
    }
}
